### ISSUE TITLE
Report is 100% inaccurate

### ISSUE THREAD

**Issue by jasonperrone** [simplecov-ruby/simplecov#1000]
I am running SimpleCov 0.21.2, Ruby 2.7.3p183, Rails 6.1.4.1.
SimpleCov is required and started first before any test runs.
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

I have 3 model tests. After they run, I look at the coverage report. It's reporting 0% coverage on the three models I wrote tests for and a host of other models BUT also reporting 100% coverage on dozens of other models that I don't even have tests for. I deleted the entire coverage directory to start from scratch, but the report is the same every time. 0% coverage for the models I wrote tests for and 100% coverage on models I don't have tests for...

Seems to only happen on model tests, not controller tests.

**Comment by samuelpismel** [comment]
Same here, 0% of coverage on any of my files. :/

**Comment by samuelpismel** [comment]
I've found a solution. The documentation is really bad about rails. The say many ways to do and don't seem to be updated with the last version of rails 6.

In my case, following the Spring config, it worked.

https://github.com/simplecov-ruby/simplecov#want-to-use-spring-with-simplecov

**Comment by jasonperrone** [comment]
Great, thank you @samuelpismel

**Comment by budu** [comment]
I've had a similar issue with Rails 7 (without Spring) and adding eager loading to my `test_helper.rb` fixed it.

**Comment by PragTob** [comment]
:wave: 

Yes that's what we talk about when we say that SimpleCov is the first thing that needs to be loaded and started. When spring is running, the models are already loaded and simplecov comes in afterwards. There's no way to track the required files then, which we need.

I added a further link to the section about spring to the README to help find this information.
