### ISSUE TITLE
branch coverage data missing after collating .resultset.json in parallel test

### ISSUE THREAD

**Issue by visu-suganya** [simplecov-ruby/simplecov#1054]
I enabled `enable_coverage :branch`
when running parallel tests, I can see that the branch coverage data generated in this step(while running parallel test)
I use SimpleCov.collate to merge all the `.resultset.json` files generated

but `SimpleCov.collate` - only merges the results only line coverage data
https://github.com/simplecov-ruby/simplecov/blob/main/lib/simplecov/result_merger.rb#L189

I need branch coverage data after collate in parallel test.

**Comment by gvn182** [comment]
same issue here

**Comment by visu-suganya** [comment]
I found the solution:
you need to call `enable_coverage :branch` before collating.
