### ISSUE TITLE
Use of ractors makes coverage non-deterministic

### ISSUE THREAD

**Issue by fdr** [simplecov-ruby/simplecov#1058]
I didn't see any previous mention of ractors in the issue tracker, so I suspect I may be the first reporter to have tried to use them. In my case, I had a short-lived ractor that would exit at some indeterminate time in the course of my test suite.

What I've found is that it makes the coverage numbers fluctuate chaotically. I suspect something like an inherited `at_exit` hook may be to blame.

If a mechanical theory for this does not jump out at you, I will try to write a minimizing test demonstrator. But I figured you may expect things to misbehave this way, and nobody has asked about it on the issue tracker yet.

**Comment by fdr** [comment]
Interesting, I didn't consider that. I'll research the matter. Maybe I'll close this until I have the time, it may still be useful to someone running a search.

**Comment by jaynetics** [comment]
I just spent quite a bit of time finding this out, so maybe this issue should stay open :)

It seems to be a problem with Ruby's own Coverage module, so I've opened an [issue in the Ruby bug tracker](https://bugs.ruby-lang.org/issues/20158).
