### ISSUE TITLE
Incorrect SimpleCov.formatter usage example in documentation

### ISSUE THREAD

**Issue by bestwebua** [simplecov-ruby/simplecov#1097]
Following to the code under the hood:

https://github.com/simplecov-ruby/simplecov/blob/903655419edee0abb4cfdbb9d0d09d0524c2abab/lib/simplecov/configuration.rb#L110-L112

For `SimpleCov.formatters` call examples in the current documentation we need to use array of formatters:

```ruby
SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::CSVFormatter,
]
```

instead of instance of `SimpleCov::Formatter::MultiFormatter`:

```ruby
SimpleCov.formatters = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::CSVFormatter,
])
```

PR: https://github.com/simplecov-ruby/simplecov/pull/1096

**Comment by PragTob** [comment]
Fixed via #1096, thanks
