### ISSUE TITLE
"Branch Coverage" with no tests reports 100% not 0% like "Line Coverage"

### ISSUE THREAD

**Issue by jasnow** [simplecov-ruby/simplecov#1110]
If you have a repo with no tests and branch coverage turned on, you get this:

Actual
  * Line Coverage: 0.0% (0 / 22)
 * Branch Coverage: 100.0% (0 / 0)
 
and I expected:
  * Line Coverage: 0.0% (0 / 22)
 * Branch Coverage: 0.0% (0 / 0)

**Comment by tycooon** [comment]
But let's say you have no branches and full line coverage, what branch coverage do you expect? :)

**Comment by jasnow** [comment]
> But let's say you have no branches and full line coverage, what branch coverage do you expect? :)

Depends on the definition of "branch", I would have guessed that you always have the main branch.
Also 0/0 is infinite so you could put "NA" or something to show that that is no value.

**Comment by jasnow** [comment]
I will close this issue as my only goal was to raise the test case.
