### ISSUE TITLE
Unable to add /app/views/* to coverage reports

### ISSUE THREAD

**Issue by onebree** [simplecov-ruby/simplecov#345]
Below is our `spec_helper.rb` file. I found how to add filters/groups on [About.com](http://ruby.about.com/od/simplecov/ss/Keeping-Organized-In-Simplecov.htm). We decided to kill Spork when running the entire test suite, so coverage reports generate for each run. (We keep Spork on for testing individual pages, for speed's sake.)

We decided to use SimpleCov because its documentation says it reports on MVC, while (before I found the About article) it only reported M&C. After adding the group, The report yields 100% on Views. Lib, and Plugins (latter 2 I did not have before), with zero files listed.

Will adding Views to the coverage report raise our percentage? If so, how can I correctly include the directory? If not, what could I do to raise the %covered to a more realistic value?

52% covered
ruby 1.9.2
rails 3.1.10
simplecov 0.7.1

``` ruby
require 'simplecov'
require 'rubygems'
require 'spork'
require 'capybara/rspec'

Spork.prefork do
  unless ENV['DRB']
    require 'simplecov'
    SimpleCov.start 'rails' do
      add_group 'Views', '/app/views/*/'
      add_filter '/app/models/legacy/'
    end
  end

  ENV["RAILS_ENV"] ||= 'test'
  require File.expand_path("../../config/environment", __FILE__)
  require 'rspec/rails'
  require 'rspec/autorun'

  Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

  Capybara.default_selector = :xpath
  Capybara.javascript_driver = :webkit

  RSpec.configure do |config|
    config.fixture_path = "#{::Rails.root}/spec/fixtures"
    config.use_transactional_fixtures = true
    config.infer_base_class_for_anonymous_controllers = false
    config.order = "random"
    config.include Helpers
  end

end

Spork.each_run do
  if ENV['DRB']
    require 'simplecov'
    SimpleCov.start 'rails'
  end

  class ActiveRecord::Base
    mattr_accessor :shared_connection
    @@shared_connection = nil

    def self.connection
      @@shared_connection || ConnectionPool::Wrapper.new(:size => 1) { retrieve_connection }
    end
  end
  ActiveRecord::Base.shared_connection = ActiveRecord::Base.connection

  User.acts_as_authentic { | c | c.maintain_sessions = false }

end
```

**Comment by bf4** [comment]
link?

**Comment by onebree** [comment]
This post links to others that I've seen as well...
http://stackoverflow.com/questions/21451540/how-do-i-get-coverage-for-views-in-rails

**Comment by bf4** [comment]
Ok, thanks.  I should add some examples of this not working to the codebase :)
