### ISSUE TITLE
Merged SimpleCov HTML Report shows 0 coverage in v0.18.0 (regression vs v0.17.1)

### ISSUE THREAD

**Issue by Justin-W** [simplecov-ruby/simplecov#854]
This is closely related to #853. See #853 for all test configuration, etc. info.

Whereas #853 describes that the XML coverage report generated from my merged coverage reports has reduced line hit counts in v0.18.0+ (vs v0.17.1), this issue is to track that the HTML report I am also generating shows zero coverage in v0.18.0+ (vs v0.17.1).

## Expected behavior

v017.1 HTML report excerpt:

```
All Files (81.69% covered at 665.54 hits/line)
41 files in total. 5756 relevant lines. 4702 lines covered and 1054 lines missed
```

v017.1 XML report excerpt:

```xml
<coverage line-rate="0.82" branch-rate="0" lines-covered="4736" lines-valid="5792" branches-covered="0" branches-valid="0" complexity="0" version="0" timestamp="1580190755">
```

## Actual behavior

v0.18.0 HTML report excerpt:

```
All Files ( 100.0% covered at 0.0 hits/line )
0 files in total.
0 relevant lines, 0 lines covered and 0 lines missed. ( 100.0% )
```

v0.18.0 XML report excerpt:

```xml
<coverage line-rate="0.15" branch-rate="0" lines-covered="867" lines-valid="5792" branches-covered="0" branches-valid="0" complexity="0" version="0" timestamp="1580254163">
```

Note that the above HTML and XML report excerpts are from the exact same CI build (and which also generated the `coverage.xml` excerpted in #853), so there seems to be some discrepancy in the reporting between the XML and HTML report formatters starting in v0.18.0.

## Related Issues

#853 A separate symptom first observed concurrently with this issue. They seem like they are probably separate regressions, but not sure.

**Comment by PragTob** [comment]
Same questions as basically on the other one, and I kinda think they are related :)

**Comment by Justin-W** [comment]
> Same questions as basically on the other one, and I kinda think they are related :)

Me, too. See my updated comments within #853 for additional info.

**Comment by PragTob** [comment]
This is on hold until we figure out #853 as I believe them to be correlated. At least the reproduction work done there will/should come in handy.

**Comment by PragTob** [comment]
Haven't heard back in a while, so closing this for now.
