### ISSUE TITLE
Coverage is empty after collate

### ISSUE THREAD

**Issue by vkodimut** [simplecov-ruby/simplecov#904]
hello,
I am running rspec and cucumber tests across multiple pods and fetching all the `.resultset.json` to merge into 1. I am using simplecov `0.18.0` inorder to use `SimpleCov.collate` method. 
I am using basic `SimpleCov.command_name SecureRandom.uuid SimpleCov.start "rails"` in my `spec_helper` and no groups or filters.
My `resultset.json` looks right with lines and branch coverage but branches are empty.

```
"f66d3979-78b9-11f4-962e-20b9c36261c3": {
    "coverage": {
      "/project/app/test.rb": {
        "lines": [
          1,
          null,
          null,
          1,
          null,
          1,
          0,
          null,
          0,
          null,
          null
        ],
 "branches": {
        }
```
When I use `SimpleCov.collate` all the resultset.json I get output like this which is empty coverage.
```
"04897be6-58dd-485f-acca-b84ce65ed556, 055ba4e8-a844-46aa-bb30-36c2b72d95f7, 1b10b6ae-51a9-4647-af89-2a801c89eec1": {
  "coverage": {
  },
  "timestamp": 1596554713
}
```
I have tried with simplecov version `0.17.1` as well and result is same.
I tried to put some debug statements and somewhere result is lost in `merge_results(*results)` method.

Please take a look at this.
Thanks!

**Comment by PragTob** [comment]
:wave: 

What's your `merge_timeout` ? This looks like it might just consider all the results "old" by the time of the merge and therefor discard them all. Try setting a super big merge time out to rule this out.

Cheers!

**Comment by vkodimut** [comment]
Sounds good.. Thanks @PragTob will try setting it and update you..

**Comment by vkodimut** [comment]
Hey @PragTob  no luck .. I added this but no luck. I put `use_merging` as well let me know if I have to remove that and give a shot. And any other things to try out.
```
SimpleCov.start "rails" do
    merge_timeout 5000
    use_merging true
  end
```

**Comment by PragTob** [comment]
@vkodimut are you sure that setting is used for your collate merging?

I'll give @deivid-rodriguez a ping as he built that feature :) 

Other than that, I'm not sure if where you put the config actually relates to collate as `colalte` has its own config: https://github.com/colszowka/simplecov#merging-test-runs-under-different-execution-environments (I haven't double checked that though, it _might_ apply depending on how the values are set)

Reading the cod though, the timeout might not affect collate so my assumption might have been wrong. It seems to only be used in the `results` method which shouldn't be triggered here, although it mi

Otherwise it might be worth checking out if the files are read/parsed correctly: https://github.com/colszowka/simplecov/blob/9056bd3852d0daca2221c9b0a964b8abada1c48c/lib/simplecov.rb#L87-L92

and/or combined correctly as to "when are they going missing":

https://github.com/colszowka/simplecov/blob/9056bd3852d0daca2221c9b0a964b8abada1c48c/lib/simplecov/result_merger.rb#L74-L81

**Comment by vkodimut** [comment]
@PragTob  No i dont think that setting is used for `collate`.. So when i added some debugging at `merge_results` method I found the below output
Sample output for `combined_result` is 
```
{"/project/app/test.rb"=>{"lines"=>[7, nil, nil, 7, nil, 7, 0, nil, 0, nil, nil]}, "/project/app/anothertest.rb"=>{"lines"=>[6, 6, nil, nil, nil, nil]}, "/project/app/tester.rb"=>{"lines"=>[6, 6, nil, nil, nil, nil]}, "/project/app/parsetest.rb"=>{"lines"=>[6, 6, nil, nil, nil, nil]},
```
Whereas the output after passing `combined_result` to `result = SimpleCov::Result.new(combined_result)` is
```
{"RSpec"=>{"coverage"=>{}, "timestamp"=>1596952869}}
```
So the results are going wrong in `SimpleCov::Result` initialize method or somewhere within it. Pls suggest.
And FYI I am using the `resultset.json` generated as part of simplecov v0.18.5 to collate.

**Comment by PragTob** [comment]
Hey, it's somewhat likely that wherever you merge the results together doesn't have access to the source code or doesn't have access to the source code under the same names:

https://github.com/colszowka/simplecov/blob/9056bd3852d0daca2221c9b0a964b8abada1c48c/lib/simplecov/result.rb#L28-L35

(see `@files`)

**Comment by vkodimut** [comment]
Thanks @PragTob  yes it worked. Atleast I am able to go past this step. After `collate` when i run the `coveralls:push` rake command I am seeing this error
```
Coveralls encountered an exception:
--
  | NoMethodError
  | undefined method `coverage' for #<SimpleCov::SourceFile:0x000000000d137b28>
  | Did you mean?  coverage_data
  | /usr/local/rvm/gems/ruby-2.7.1/bundler/gems/coveralls-ruby-e6c2b34bea94/lib/coveralls/simplecov.rb:42:in `block in get_source_files'
```
Need help on this ...

**Comment by vkodimut** [comment]
Thanks @PragTob I was able to go past this step.. I am using Coveralls to push the coverage data after formatting `Coveralls::SimpleCov::Formatter` .. When I try to push the collated result I get below error. Need some help.
```
NoMethodError
--
  | undefined method `coverage' for #<SimpleCov::SourceFile:0x000000000d137b28>
  | Did you mean?  coverage_data

```

**Comment by PragTob** [comment]
@vkodimut that's the coveralls formatter so not out code, it's likely relying on something removed/refactored that either I wasn't aware of or that was never intended to be public. I can have a double look/check if it's worth reinstating redirecting but that'd take some time.

**Comment by vkodimut** [comment]
I lowered the simplecov version and it worked.. Thanks for all your help @PragTob  !!

**Comment by PragTob** [comment]
@vkodimut if I get the time I'll check if I can bring it back easily in the next release, otherwise you/we'd probably have to file an issue with the coveralls gems.

That said, I also need to improve our docs on what's considered public and what isn't.
