### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by sandstrom** [simplecov-ruby/simplecov#907]
Thanks for an awesome project! 🏅 

Maybe we could drop 1.9+ from the description (that's virtually everyone these days and mentioning 1.9+ makes the project feel a bit dated), to something like this:

> Code coverage for Ruby with a powerful configuration library and automatic merging of coverage across test suites

**Comment by PragTob** [comment]
I was gonna say "yup done", thanks!

But, I don't have the rights to do so. Well, as good a reason as any to ping @colszowka again about moving the repo over to an org :sweat_smile:

**Comment by PragTob** [comment]
Anddd done!
