### ISSUE TITLE
missing dependency on 'json'

### ISSUE THREAD

**Issue by and0x000** [simplecov-ruby/simplecov#917]
simplecov requires the gem `json` but does not list it as a dependency.

https://github.com/simplecov-ruby/simplecov/blob/main/lib/simplecov/last_run.rb#L3
https://github.com/simplecov-ruby/simplecov/blob/main/lib/simplecov/result_merger.rb#L3

This can become a problem, as `json` is not necessarily installed with ruby, e.g. on alpine.

```
docker run --rm -ti alpine:edge /bin/sh                  
/ # apk --update add ruby
[...]
/ # ruby -v 
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
/ # gem list | grep json
/ # gem install simplecov pry
Fetching simplecov-html-0.12.2.gem
Fetching simplecov-0.19.0.gem
Fetching docile-1.3.2.gem
Successfully installed docile-1.3.2
Successfully installed simplecov-html-0.12.2
Successfully installed simplecov-0.19.0
Fetching method_source-1.0.0.gem
Fetching coderay-1.1.3.gem
Fetching pry-0.13.1.gem
Successfully installed coderay-1.1.3
Successfully installed method_source-1.0.0
Successfully installed pry-0.13.1
6 gems installed
/ # pry
[1] pry(main)> require 'simplecov'
LoadError: cannot load such file -- json
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Caused by LoadError: cannot load such file -- simplecov
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**Comment by PragTob** [comment]
:wave: 

Hi there and thanks for reporting an issue.

Excuse m language but WTF. `json` is part of the standard library, the point of the standard library being that these packages are available everywhere. I know alpine is focussed on being very small but this just seems to repeat the fault of other linux distributions where they slice up ruby into multiple packages which (imo) is one of the reasons no one is using the ruby packages provided.

Is there some ruby-full package people can install instead?

I'm not sure it's in the best interest of everyone of adding dependencies to stdlib ruby gems to all projects. Imo this pushes the choices of some distribution to all the gem maintainers of an entire eco system. 

I'll have to think about this.

**Comment by and0x000** [comment]
Hi and thanks for the quick reply.

There is the `ruby:alpine` image, which comes with both, `json` and `etc` installed by default, but it doesn't work for my case, as it ships older packages than `alpine:edge`.
On alpine itself, there are indeed the packages [`ruby`](https://pkgs.alpinelinux.org/packages?name=ruby&branch=edge) and [`ruby-full`](https://pkgs.alpinelinux.org/packages?name=ruby-full&branch=edge) (which seems a meta-package). 
Thank you for the hint, using `ruby-full` works for my case.

thoughts on the alpine side:
If these packages are standard library I would have expected the package `ruby` to ship with them. I think it is a bit counter-intuitive the way it is. Solving it with the meta-package way, I would have preferred `ruby` being the meta package which includes the full standard library and e.g. `ruby-minimal` being the very minimum without json, etc, ...

thoughts on the ruby side:
If I had to argue for the approach in alpine, I would probably say, that something that you can strip off a language or that you need to `require`, should not be part of the standard library and therefore listed as dependency.

Being at the user end and not involved to any qualifying depth whatsoever with any of these projects, this is just some personal view.

**Comment by PragTob** [comment]
yeah, thanks for the report but I'm gonna close this. It's a weird thing some linux distros do, there's usually an easy workaround and adding them manually produces potentially quite some headache or incompatibility for us. Closing.

**Comment by deivid-rodriguez** [comment]
I just found out that `simplecov` actually depended on `json` and I removed it :see_no_evil:. I think that was a mistake on my part.

I also believe thought that OS packages should fix this and include all default libraries by default. I've seen problems like this in the past on different distributions, and they have fixed them when I reported them.

> If these packages are standard library I would have expected the package ruby to ship with them. I think it is a bit counter-intuitive the way it is. Solving it with the meta-package way, I would have preferred ruby being the meta package which includes the full standard library and e.g. ruby-minimal being the very minimum without json, etc, ...

This sounds like the most sane approach to me, but it probably has a too tricky compatibility path. It might be worth to report the idea to alpine though.

**Comment by PragTob** [comment]
@deivid-rodriguez I think the dependency on json was for legacy ruby version support reasons as `json` is newer to the stdlib or some issue like this.

I've kept thinking about this as well though and if adding the dependency just works and if added as just `gem "json"` doesn't trigger any installs or what not (as it finds it in the stdlib, I have never tried this) then I might be fine with it as then it also shouldn't introduce any version incompatibilities. Like what I worried about was people setting version requirements on it that are somewhat arbitrary and then conflict.

I'm just worried that it'll introduce some problem that I haven't thought about yet :sweat_smile:

**Comment by and0x000** [comment]
> This sounds like the most sane approach to me, but it probably has a too tricky compatibility path. It might be worth to report the idea to alpine though.

There actually seems to be an issue on alpine's gitlab, where I noted this https://gitlab.alpinelinux.org/alpine/aports/-/issues/11721
