### ISSUE TITLE
0.19.0 change of `Result.from_hash` broke our coverage merging

### ISSUE THREAD

**Issue by mobilutz** [simplecov-ruby/simplecov#920]
**NOTE:** This is NOT an issue, that breaks our implementation anymore.
This ticket is more created to talk about this topic as mentioned here as well: https://github.com/simplecov-ruby/simplecov/pull/913#issuecomment-677437282

The behaviour change in v0.19.0 for `Result.from_hash` lead to some problem on the way we merge our ruby coverages.

This is the PR that for us was an unexpected change, specifically the change that the method now returns an array instead of a `Result` object.
https://github.com/simplecov-ruby/simplecov/pull/913

Maybe it is good, to describe how we use `Result.from_hash`.
This is the code, that broke for us:
```
results = []
all_results = Dir['/tmp/coverage/.resultset*.json']
all_results.each do |result_file_name|
  puts "Processing #{result_file_name}"
  results << SimpleCov::Result.from_hash(JSON.parse(File.read(result_file_name)))
end

SimpleCov::ResultMerger.merge_results(*results).format!
```

**What exactly does this code do?**

We are running our ruby suite on 8 different processes which produce 8 different `.resultset.json` files. After all of them are created, we combine them with the code above.
This code was written almost 2 years ago, and worked without any problems. I am not sure anymore, what other ways of merging the different results has been tried back then. Even though I worked on that, I cannot remember. The only thing I do remember is, that this code lead to a complete HTML coverage report generation, and the others did not.

Maybe there is an easier way to combine results from different runs, that do not share the same storage possibilities except S3.

PS: We now "solved" this situation by replacing the `<<` inside the code above to `+=`. So it was not too hard for us to bring back our functionality - the hard part was finding what needed to be changed!

**Comment by PragTob** [comment]
👋 

so what you do is eerily similar to what we do in `collate` and also to how I changed it. I'd recommend you to do a map, or just start using our collate: https://github.com/simplecov-ruby/simplecov/pull/913/files#diff-107ed4983c51dd50042b98843dbaad97R85-R94

collate docs: https://github.com/simplecov-ruby/simplecov#merging-test-runs-under-different-execution-environments

How are you running the 8 processes? With `parallel_tests` then it should work without any changes.

I believe even if you don't use parallel tests and just run 8 test processes with appropriately different `command_name`'s and a big merge_timeout it should be merged correctly (- existing race conditions): https://github.com/simplecov-ruby/simplecov#merging-test-runs-under-the-same-execution-environment

Cheers,
Tobi

**Comment by mobilutz** [comment]
We are using HerokuCI as our CI, and there the 8 independent "containers" are running in total separation. We use `knapsack` to distribute the specs to the so called nodes, and inside every node, we copy the `.resultset` to an S3 bucket.
When the bucket (folder) has 8 `.resultset.json` files, we merge them together.

I already tried to use `collate`, but when I run it like in the linked suggestion, the coverage-html that comes out of it is empty. But maybe I am just missing some configuration/setup.
All the resultsets have a uniq name, so that is node the problem. Example:
```json
{
  "NODE 1 of 8": {
    "coverage": { [...] },
    "timestamp": 1597750265
  }
}
```

**Comment by PragTob** [comment]
@mobilutz that is very weird... it's made exactly for that use case so either it's a bug or some thing required that we haven't documented as good as it could be. Off the top off my head:

* were you're trying to merge, does it have access to the source code files under the path as shown in the coverage data?

hm no that's the only thing I can come up with... iirc it doesn't look at timeout times. 

If you did a bit of debugging where it went wrong that'd be great but I know it takes time and you have a working solution. I'm not sure I can be of help, as I'd need the source code to fully see it work. theoretically a sample repo with 2 resultset jsons and some dummy files were collate doesn't work would be enough though.

I'm also gonna @deivid-rodriguez as he did a lot of the collating :+1: :grin:

**Comment by sterankin** [comment]
> @sterankin I believe in your case the problem is that all the command names are the same (all rspec), please check the section about test suite names: https://github.com/simplecov-ruby/simplecov#test-suite-names

Thanks - I think you could be right.  I changed each test group to have a unique name through the environment variable.
However I am seeing the following result:

```
{
  "Job RSpec:GroupA, Job RSpec:GroupB, Job RSpec:GroupC, Job RSpec:GroupD": {
    "coverage": {
    },
    "timestamp": 1598350485
  }
}
```

I think this is an issue because of the file paths.  Our RSpec tests run in Docker containers, and therefore the .resultset.json file has the following paths:
```

 "coverage": {
      "/usr/src/app/lib/core_ext/array.rb":
```

However once I try and collate all the .resultset.json files, the path of `usr/src` does not exist and it cannot find the code files - does this mean Simplecov will not output results?

**Comment by PragTob** [comment]
@sterankin yup absolutely right, simplecov needs the files to process things like disabling coverage or well display them in the HTML formatter etc... we should build a solution for that as I think it's rather common... like.. I dunno... either paths relative from the root directory or rewrite paths or something,

**Comment by sterankin** [comment]
> @sterankin yup absolutely right, simplecov needs the files to process things like disabling coverage or well display them in the HTML formatter etc... we should build a solution for that as I think it's rather common... like.. I dunno... either paths relative from the root directory or rewrite paths or something,

I solved my issue by also running the SimpleCov collate in Docker also.  However I have just found out that Sonar does not understand the new .resultset.json file introduced in Simplecov 0.18:

https://community.sonarsource.com/t/ruby-coverage-simplecov-json-file-does-not-work/20909/6

I can't go back to 0.17 since I need the collate functionality.  Any ideas - does the json structure differ, could I monkey patch something?

**Comment by deivid-rodriguez** [comment]
Sonar should add support for recent simplecov versions. [The discussion in codeclimate's test-reporter's repository](https://github.com/codeclimate/test-reporter/issues/413) probably applies to sonar in a similar way. To circumvent that and and upgrade now, you can convert the resultset file manually to the old format. Here's a script to do it: https://gist.github.com/qortex/7e7c49f3731391a91ee898336183acef#file-transform-rb.

**Comment by mobilutz** [comment]
> @sterankin yup absolutely right, simplecov needs the files to process things like disabling coverage or well display them in the HTML formatter etc... we should build a solution for that as I think it's rather common... like.. I dunno... either paths relative from the root directory or rewrite paths or something,

@PragTob This is actually the situation that I didn't know. SimpleCov is expecting the results to have absolute paths.

I tried `collate` locally, without changing the paths in the `.resultset.json` files which of course then meant to output at all. I compared that to our working (fixed) solution on CI, which resulted in a correct coverage report.

After I create this repo, which I would have hoped to show the problem between `collate` and our `custom-merger`, I saw that the problem was "just" the incorrect absolute paths.

Maybe some information on this could be added.

PS: Here is the repo I created: https://github.com/mobilutz/simplecov-issue-920
NOTE that to really test the coverage merge/collate, one needs to change the path inside the two `.resultset.json` files ;)

**Comment by PragTob** [comment]
@mobilutz thanks!

Yeah absolutely I think what needs to be done here is the following:

1. document this current limitation better
2. provide an easy way to circumvent this limitation, I guess absolute paths were introduced/used for a reason. So not sure we could just fall back to relative paths... might require a bit of digging though. Alternatively, optionally enabling relative paths or some sort of path replace mechanism might be enough of a solution.

I'd probably move that to another issue though... there's actually loads of issues I should still create :|

Might take some time tomorrow!

**Comment by FGoessler** [comment]
We ran into the same issue with our setup on CircleCI and were able to fix it for now using the changes initially mentioned by @mobilutz on our merging code. Thanks for pointing us there!

FYI: We based our stuff off this gist: https://gist.github.com/trev/9cc964a54c8d5b62f4def891eba6b976

**Comment by PragTob** [comment]
@FGoessler is there anything keeping you from using straight up `SimpleCov.collate` ? That's what I'd  recommend everyone to switch to :D

**Comment by mobilutz** [comment]
I will close this ticket now, as the problem is purely on our side.

Nevertheless would the followup tickets be very good to have @PragTob.
Thanks again for your feedback!
