### ISSUE TITLE
Can't get any result from subprocess coverage

### ISSUE THREAD

**Issue by Pr0p1k** [simplecov-ruby/simplecov#924]
If I got it right, `SimpleCov#enable_for_subprocesses` can track every forked process, but I get these results: 
![image](https://user-images.githubusercontent.com/31842542/91830294-44d91080-ec4b-11ea-9906-9d6629eb3158.png)
As you can see, forked processes aren't covered. 

Enabled subprocess coverage like this: 
```
SimpleCov.start do
      SimpleCov.enable_for_subprocesses true
end
```
What am I doing wrong?

**Comment by PragTob** [comment]
Hi there,

please double check the docs there's a whole section of what you gotta configure: https://github.com/simplecov-ruby/simplecov#running-simplecov-against-subprocesses

**Comment by Pr0p1k** [comment]
I missed it, I am sorry .~.
