### ISSUE TITLE
Merging index.html from multiple build machines 

### ISSUE THREAD

**Issue by vkodimut** [simplecov-ruby/simplecov#935]
Howdy! 
This is not an issue but a question. I would like to merge all `index.html` from multiple build machines into one. Is there a way to accomplish this?
I am using `simplecov = 0.17.0` since upgrading to `0.18` will break few stuffs. And merging the result using `SimpleCov::ResultMerger.merge_results(*results)`. I am able to merge all `.resultset.json` into single file. Does it works for `index.html` and assets too. 
Or is there a way I can generate a good html report just by using this merged `resultset.json`

Thanks in advance !

**Comment by vkodimut** [comment]
@PragTob   pls provide your input..

**Comment by tycooon** [comment]
You can just run `SimpleCov.collate` and provide it with a set of your `resultset.json` files. It will merge everything and generate a report using your configured formatters (including HTML one).

**Comment by tycooon** [comment]
See https://github.com/simplecov-ruby/simplecov#merging-test-runs-under-different-execution-environments

**Comment by vkodimut** [comment]
Right.. but as mentioned above  I am using older version of simplecov `0.17.0` and using `ResultMerger` to merge results.

**Comment by vkodimut** [comment]
Yep was about to comment that 👍  .. I tried this 
```
 result = SimpleCov::ResultMerger.merge_results(*results)
   SimpleCov.formatter = SimpleCov::Formatter::HTMLFormatter
    SimpleCov.result.format!
    SimpleCov::ResultMerger.store_result(result)
```
But I get `Coverage report generated for  to /project/coverage. 0.0 / 0.0 LOC (100.0%) covered.` so no coverage is generated.

**Comment by tycooon** [comment]
There are full file paths in `resultset.json` files. Do you have them in place in a filesystem when merging results?

**Comment by vkodimut** [comment]
Not actually.. I have several build pods with test running and from each of them I am copying `.resultset.json` and merging into single json file after `test` stage is done.

**Comment by tycooon** [comment]
This might be the problem, SimpleCov currently needs those file to work properly.

**Comment by vkodimut** [comment]
I was able to generate by reordering the formatter.. Thanks for all the help !!

**Comment by PragTob** [comment]
Thanks @tycooon for helping out in my absence and glad this could be resolved!

![WhatsApp Image 2020-07-19 at 07 29 15](https://user-images.githubusercontent.com/606517/96377450-145f1e80-1186-11eb-92c2-7fe53a776b4a.jpeg)
