### ISSUE TITLE
No coverage for any statements inside any method

### ISSUE THREAD

**Issue by hyunwoona** [simplecov-ruby/simplecov#937]
Hi guys!

Please help me with this issue. The codebase is pretty large, and I know at least some parts of it has decent test coverage. However every statement inside every method is red like in the screenshot.

<img width="831" alt="Screenshot 2020-10-12 at 22 40 53" src="https://user-images.githubusercontent.com/3788978/95819970-0d469500-0cdc-11eb-8d06-df6cca07ec21.png">

I required it inside Rakefile, and tried both Test::Unit and Minitest (since we are migrating to Minitest).
I ran the tests using `bundle exec rake test` and just `rake test`, but got the same result.

Do you know why this is happening? I can provide more information as needed. Thank you so much!

**Comment by PragTob** [comment]
:wave: 

Hi there, sorry for the silence not able to dedicate a ton of time to open source these days.

It's tough to say what's up, this looks kinda like these methods aren't executed while simplecov is started. Have you started simplecov?

Have you tried the troubleshooting tips provided here? https://github.com/simplecov-ruby/simplecov#troubleshooting

**Comment by hyunwoona** [comment]
@PragTob Thank you for your response. It's imported and started at the top of the Rakefile. I'm using Minitest and I have no test_helper file (there's one but it's local to a subset of test suite, and putting it there didn't work either). I looked at the troubleshooting tips but it didn't help. Can it be used when the tests are run as rake tasks?

**Comment by hyunwoona** [comment]
Now I'm getting `SimpleCov failed to recognize the test framework and/or suite used. Please specify manually using SimpleCov.command_name 'Unit Tests'.` this error. Do you support Minitest?

**Comment by matoakley** [comment]
I've been experiencing the same issue using Rails 6 and have found that disabling parallel tests in `test_helper.rb`resolves the issue.
