### ISSUE TITLE
Getting started for server processes instructions unclear

### ISSUE THREAD

**Issue by DeuterGraves** [simplecov-ruby/simplecov#944]
I'm running RSpec on a Rails 6 app, I've set up simplecov and found that I was failing my CI tests because of the way I understood the set up instructions here in the readme: 

> SimpleCov must be running in the process that you want the code coverage analysis to happen on. When testing a server process (e.g. a JSON API endpoint) via a separate test process (e.g. when using Selenium) where you want to see all code executed by the rails server, and not just code executed in your actual test files, you'll want to add something like this to the top of bin/rails, but below the "shebang" line (#! /usr/bin/env ruby):

```
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails'
  puts "required simplecov"
end
```

Which lead me to set up `bin/rails` like this: 
```
#!/usr/bin/env ruby
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails'
  puts "required simplecov"
end
begin
```

which failed my CI process because the gems hadn't loaded yet.  Once moved further down in the file, under the `require_relative '../config/boot'` line it worked a treat. 

```
require_relative '../config/boot'
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails'
  puts "required simplecov"
end
```

Better still when I moved it to the bottom of `boot.rb`

```
require "bundler/setup" # Set up gems listed in the Gemfile.
require "bootsnap/setup" # Speed up boot time by caching expensive operations.

if ENV["RAILS_ENV"] == "test"
  require "simplecov"
  SimpleCov.start "rails"
  puts "required simplecov"
end
```

I'd suggest a minor change to the readme - hastily edited here: 

>SimpleCov must be running in the process that you want the code coverage analysis to happen on. When testing a server process (e.g. a JSON API endpoint) via a separate test process (e.g. when using Selenium) where you want to see all code executed by the rails server, and not just code executed in your actual test files, you'll want to add something like this to the top of bin/rails, after `config/boot` is required :
```
if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'
  SimpleCov.start 'rails'
  puts "required simplecov"
end
```

**Comment by PragTob** [comment]
Hi there,

thanks we'll add it. Even better, we'd have an executable example in the repo but that's another topic :) 

For changes like this in the future also feel free to open a PR :slightly_smiling_face:
