### ISSUE TITLE
Files not correctly ignored

### ISSUE THREAD

**Issue by tianhaoz95** [simplecov-ruby/simplecov#975]
Please see  https://github.com/tianhaoz95/fastlane-plugin-flutter_version/issues/67 for the original issue and https://community.codecov.io/t/codcov-not-tracks-ignored-files-in-my-ruby-project/2416 for more input from the codecov side.

**Comment by PragTob** [comment]
Hi there and thanks for your report.

More detail directly in the issue would be helpful for a maintainer so I don't have to go around the links as well as every other person getting here.

`track_files` just says which files should absolutely be tracked, it does not indeed ignore files. Please use `add_filter`.
