### ISSUE TITLE
Question: plans to support Ruby 3?

### ISSUE THREAD

**Issue by agalloch** [simplecov-ruby/simplecov#988]
Hello and thank you for this wonderful gem 🙇‍♂️ !

I see latest (as of today) `simplecov` gem depends on `simplecov-html@0.11` which is [locked to](https://github.com/simplecov-ruby/simplecov-html/blob/v0.11.0/simplecov-html.gemspec#L17) Ruby v2.4.

I've looked around both repos (change logs, issues, PRs) but couldn't find any information of Ruby 3 support. Do you plan to add it in foreseeable future?

Thank you! 🙂

**Comment by tycooon** [comment]
Currently maintainers are not available, so you can just use master branch as for now.

**Comment by agalloch** [comment]
@tycooon, master (`main`) branch also [depends on](https://github.com/simplecov-ruby/simplecov/blob/a302b78888337e6dc1d86671133b1679ebeb3c7b/simplecov.gemspec#L39) `simplecov-html@0.11` so it too is not Ruby 3 compatible. Do I miss something? 🙂

**Comment by tycooon** [comment]
It depends on `~> 0.11` which is basically anything below `1.0`. You can try the following in your Gemfile:

`gem "simplecov-html", github: "simplecov-ruby/simplecov-html"`

**Comment by agalloch** [comment]
Many thanks, @tycooon, your suggestion worked! Happy Easter!
