### ISSUE TITLE
Result creation slow due to File.file? check

### ISSUE THREAD

**Issue by Sprunth** [simplecov-ruby/simplecov#990]
Hi, I've been investigating slow runs of simplecov on a large codebase, and I've tracked it down to this [line](https://github.com/simplecov-ruby/simplecov/blob/main/lib/simplecov/result.rb#L34). Specifically, the `File.file?` check.

I don't have full context here, but is the check necessary? In my tests, it's 95%+ of the time is spent here for a `SimpleCov.collate` call.

Here's my basic test results from a smaller codebase.
```
      start = Time.now
      @files = SimpleCov::FileList.new(result.map do |filename, coverage|
        SimpleCov::SourceFile.new(filename, JSON.parse(JSON.dump(coverage))) if File.file?(filename)
      end.compact.sort_by(&:filename))
      puts "Finish. Time spent: #{Time.now - start}. File count: #{result.size}"
```
`Finish. Time spent: 27.383851. File count: 1443`

```
      start = Time.now
      @files = SimpleCov::FileList.new(result.map do |filename, coverage|
        SimpleCov::SourceFile.new(filename, JSON.parse(JSON.dump(coverage))) #if File.file?(filename)
      end.compact.sort_by(&:filename))
      puts "Finish. Time spent: #{Time.now - start}. File count: #{result.size}"
```
`Finish. Time spent: 0.014051. File count: 1443`

Ruby versions I've tried
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]

Gemfile
simplecov (0.21.2)

**Comment by ptrippett** [comment]
Hi @Sprunth 

I dont see this happening on Linux and from what I can see from your ruby versions your on mac. As File.file? is a ruby method my first guess would be this is something on you particular machine causing it, virus scanner, overlay fs, virtual machine or something similar. Can it be reproduced on a different machine?

Thanks

**Comment by Sprunth** [comment]
Hey @ptrippett thanks for taking a look.
There is a virus scanner on my system but I originally took a look because we've seen slow coverage generation on our jenkins builds (containered linux, I believe).

I can try monkey-patching the gem to get benchmarking data, but was hoping to figure out if this File? check was even needed.

**Comment by Sprunth** [comment]
I went back to benchmark via monkey patching, and indeed this line is fast on our jenkins build. Thanks again for the help
