### ISSUE TITLE
Filtering-out test directory in models

### ISSUE THREAD

**Issue by RaviPatel** [simplecov-ruby/simplecov#991]
We have a rails app that has a `Test` model with directory structure:
```
 app/models/test/form.rb
 app/models/test/assertions/assertion.rb
 app/models/test/assertions/...
```

test_helper.rb has this config for SimpleCov:
```
SimpleCov.start 'rails' do
  add_filter '/app/middleware/'
  add_filter '/bin/'
  add_filter '/db/'
  add_filter '/protobuf/'

  add_group 'System Tests', ['app/channels', 'app/controllers', 'app/helpers']
  add_group 'Unit Tests', [
    'app/datatables',
    'app/jobs',
    'app/mailers',
    'app/models',
    'app/policies',
    'app/presenters',
    'app/serializers',
    'app/services',
    'lib'
  ]

  enable_coverage :branch
  maximum_coverage_drop 1
  minimum_coverage 80
end
```

The Gemfile.lock:
```
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov-rcov (0.2.3)
      simplecov (>= 0.4.1)
    simplecov_json_formatter (0.1.2)
```

Despite not having `add_filter '/test/'`, nothing in the `app/models/test` dir is being included in the test coverage. It looks like all /test/ dirs are automatically be filtered-out by SimpleCov? How can we get around this?

**Comment by ptrippett** [comment]
Would a splat work? `'app/models/**/*'` ?

**Comment by RaviPatel** [comment]
> Would a splat work? `'app/models/**/*'` ?

How/where would we add this? The "Unit Tests" group explicitly adds 'app/models' but still not adding the test/ dir

**Comment by RaviPatel** [comment]
Adding `filters.clear` did the trick for me
